{"name": "Тест попытки получения списка заказов пользователя (без авторизации)", "status": "passed", "description": "Запрос получения списка заказов пользователя без авторизации возвращает ошибку Unauthorized", "steps": [{"name": "Отправляем запрос на создание заказа", "status": "passed", "parameters": [{"name": "payload", "value": "{'ingredients': ['61c0c5a71d1f82001bdaaa6c']}"}], "start": 1717607915006, "stop": 1717607915960}, {"name": "Отправляем запрос на получение заказов пользователя", "status": "passed", "start": 1717607915962, "stop": 1717607916989}], "start": 1717607914903, "stop": 1717607916991, "uuid": "78774049-3c1a-424d-bae5-fd2882417227", "historyId": "fcf3161122fa1d9f66cf504e46683fff", "testCaseId": "fcf3161122fa1d9f66cf504e46683fff", "fullName": "tests.test_orders.TestOrders#test_get_user_orders_without_authorization_return_unauthorized_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_orders"}, {"name": "subSuite", "value": "TestOrders"}, {"name": "host", "value": "DESKTOP-9PI1IG9"}, {"name": "thread", "value": "5516-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_orders"}]}